name = "mrx-app-builder"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "KV"
id = "87974f4fff0a4525a4663b0ad8852ca7"
preview_id = "87974f4fff0a4525a4663b0ad8852ca7"

[vars]
DASHBOARD_URL = "https://mrx-app-builder.pages.dev"
